---
- hosts: all 

  tasks:
      - name: Import postgres10 repos
        command: "yum install -y https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm"
        become: yes
        ignore_errors: yes

      - name: Install Yum Repos.
        yum: name={{ item }} state=present
        with_items:
            - postgresql10
            - postgresql10-server
            - postgresql10-contrib
            - postgresql10-devel
            - python-devel
            - git
            - gcc
        become: true

      - name: Install Python.
        yum: name=python state=present
        become: true

      - name: Install psycopg.
        shell: git clone https://github.com/psycopg/psycopg2.git && python /home/vagrant/psycopg2/setup.py build 
        shell: rm -rf /home/vagrant/psycopg2

      - shell: ls /var/lib/pgsql/10/data 
        register: data_files
        become: true

      - name: Initialize Postgres
        shell: /usr/pgsql-10/bin/postgresql-10-setup initdb
        when: data_files.stdout == ""
        become: true

      - name: Enable Postgres
        systemd: name=postgresql-10 state=started
        become: true


